<?php

$str='riddhi';
$i=0;
//@ error control operator: it will cause error messages generated by that expression to be ignored
while(@$str[$i]!='')
{
	$i++;
}
echo "string length is: $i<br>";
?>

<?php
$str='geeta#';
$i=0;

while($str[$i]!='#')
{
	$i++;
}
echo "string length is: $i";

?>